### ISSUE TITLE
Error in following links

### ISSUE THREAD

**Issue by minimenchmuncher** [emilyaviva/eakm-website-gatsby#1]
When I press a link to go to an external site (such as the links in "talks"), then try to return by using the back button, I get a 404 error.

Similarly, I can't directly get to [http://emilyaviva.com/talks](http://emilyaviva.com/talks) or [http://emilyaviva.com/portfolio](http://emilyaviva.com/portfolio) directly; and if I'm on any of those pages, if I hit the "refresh" button, I get a 404 as well.

Using Firefox 46.0.1

**Comment by emilyaviva** [comment]
Updated Gatsby and made a whole slew of other changes. Right now there's nothing at `/portfolio` or any other links, but the routing should (famous last words) be fixed.

**Comment by emilyaviva** [comment]
I added a route at `/contact` (the first of several) and it works.
